/* Awesome Airway — curated dataset.
 * A general survey / awesome-list of pulmonary airway analysis from chest CT:
 * segmentation, topology/connectivity, anatomical labeling, navigation,
 * datasets & challenges. (ATM26 is one of several challenges, not the focus.)
 *
 * Edit PAPERS to add methods. Fields marked with a trailing comment "[unverified]"
 * were sourced from search snippets and should be checked against the source page
 * before citing. Run update_repos.py to refresh GitHub star counts.
 */
window.AWESOME_AIRWAY = {
  GENERATED_AT: "2026-07-07",

  CATEGORIES: {
    segmentation: {
      name: { zh: "气道分割 (深度学习)", en: "Airway Segmentation (Deep Learning)" },
      short: { zh: "分割", en: "Seg" },
      desc: { zh: "从胸部 CT 直接分割二值气道掩膜的深度学习方法。核心挑战是类别极度不平衡、远端细支气管易漏检、以及大视野下的显存/感受野权衡。对应 ATM26 Track 1。",
              en: "Deep-learning methods that segment a binary airway mask directly from chest CT. Key challenges: extreme class imbalance, easily-missed distal bronchioles, and the memory/receptive-field trade-off over large volumes. Corresponds to ATM26 Track 1." },
    },
    topology: {
      name: { zh: "拓扑 / 连通性保持", en: "Topology & Connectivity" },
      short: { zh: "拓扑", en: "Topo" },
      desc: { zh: "针对气道树管状结构，通过连通性损失、中心线/骨架监督、断裂修复等手段保证分割结果的拓扑正确性——这是 ATM 系列评价（树长检出、分支检出）的核心。",
              en: "For the tubular airway tree, ensuring topological correctness via connectivity losses, centerline/skeleton supervision and break repair — the core of the ATM-series metrics (tree-length & branch detected)." },
    },
    labeling: {
      name: { zh: "解剖分支标注", en: "Anatomical Branch Labeling" },
      short: { zh: "标注", en: "Label" },
      desc: { zh: "为气道分支分配标准解剖名称（段支气管 RB1–10 / LB1–10 等），常用图/树神经网络或 Transformer 建模气道树的层级拓扑。对应 ATM26 Track 2。",
              en: "Assigning standard anatomical names to branches (segmental bronchi RB1–10 / LB1–10, etc.), typically with graph/tree neural nets or Transformers modeling the airway-tree hierarchy. Corresponds to ATM26 Track 2." },
    },
    transformer: {
      name: { zh: "Transformer / 状态空间 / 基础模型", en: "Transformer / SSM / Foundation Models" },
      short: { zh: "TF/SSM", en: "TF/SSM" },
      desc: { zh: "基于注意力、Mamba 状态空间或基础模型（foundation model）的新一代气道分析方法（2024–2026）。",
              en: "Next-generation airway methods (2024–2026) based on attention, Mamba state-space models, or foundation models." },
    },
    navigation: {
      name: { zh: "支气管镜导航 / 中心线", en: "Bronchoscopy Navigation / Centerline" },
      short: { zh: "导航", en: "Nav" },
      desc: { zh: "面向支气管镜介入的气道中心线提取、路径规划与实时定位方法——ATM26 的下游临床应用场景。",
              en: "Airway centerline extraction, path planning and real-time localization for bronchoscopic intervention — the downstream clinical use case of ATM26." },
    },
    dataset: {
      name: { zh: "数据集与挑战赛", en: "Datasets & Challenges" },
      short: { zh: "数据集", en: "Data" },
      desc: { zh: "公开气道 CT 数据集与相关挑战赛综述论文。",
              en: "Public airway CT datasets and related challenge/benchmark papers." },
    },
  },

  // ------------------------------------------------------------------ TIMELINE
  TIMELINE: [
    { date: "2026-06-15", event: { zh: "官网 & 报名开放", en: "Website & registration opened" }, note: { zh: "网站与报名通道开放", en: "Website and registration opened" }, done: true },
    { date: "2026-04-24", event: { zh: "数据集发布 (Zenodo)", en: "Dataset released (Zenodo)" }, note: { zh: "训练数据 Task1 / Task2", en: "Training data Task1 / Task2" }, done: true },
    { date: "2026 (TBD)", event: { zh: "Sanity-check 阶段开放", en: "Sanity-check phase opens" }, note: { zh: "提交流程验证", en: "Submission pipeline check" }, done: false },
    { date: "2026 (TBD)", event: { zh: "最终测试阶段", en: "Final test phase" }, note: { zh: "最终测试提交", en: "Final test phase submission" }, done: false },
    { date: "2026-09-27 ~ 10-01", event: { zh: "MICCAI 2026 · 斯特拉斯堡", en: "MICCAI 2026 · Strasbourg" }, note: { zh: "SENSAR 网络挑战赛活动", en: "SENSAR Network challenge event" }, done: false },
  ],

  // ------------------------------------------------------ OFFICIAL REQUIRED REFS
  OFFICIAL_REFS: [
    {
      title: "Multi-site, Multi-domain Airway Tree Modeling (ATM'22 挑战赛综述)",
      authors: "Zhang M., Wu Y., Zhang H., Gu Y., et al.",
      year: 2023, venue: "Medical Image Analysis, 90:102957",
      category: "dataset", star: true,
      idea: { zh: "ATM'22 挑战赛官方综述：多中心/多域气道树建模基准，系统比较各队分割方法与拓扑指标，是 ATM26 的直接前身。", en: "The official ATM'22 challenge summary: a multi-site/multi-domain airway-tree-modeling benchmark systematically comparing teams' methods and topology metrics; the direct predecessor of ATM26." },
      arxiv: "2303.05745", doi: "10.1016/j.media.2023.102957",
      code: "https://github.com/EndoluminalSurgicalVision-IMR/ATM-22-Related-Work",
      tags: ["ATM22", "benchmark"],
    },
    {
      title: "Reflecting Topology Consistency and Abnormality via Learnable Attentions for Airway Labeling",
      authors: "Li C., Zhang M., Zhang C., Gu Y.",
      year: 2025, venue: "IJCARS 20(7):1315-1323 (IPCAI 2025)",
      category: "labeling", star: true,
      idea: { zh: "可学习注意力建模气道树拓扑一致性并显式标记解剖异常/离群分支，用于段支气管命名。ATM26 Track 2 官方参考。", en: "Learnable attentions model airway-tree topology consistency and explicitly flag anatomical abnormalities/outliers for segmental branch naming. An ATM26 Track 2 official reference." },
      arxiv: "2410.23854", doi: "10.1007/s11548-025-03368-3",
      code: "https://github.com/EndoluminalSurgicalVision-IMR/Reflecting-Topology-Consistency-and-Abnormality-via-Learnable-Attentions",
      tags: ["attention", "outlier"],
    },
    {
      title: "AirMorph: Topology-Preserving Deep Learning for Pulmonary Airway Analysis",
      authors: "Zhang M., Li C., et al. (Yun Gu group)",
      year: 2024, venue: "arXiv preprint (rev. 2025)",
      category: "transformer", star: true,
      idea: { zh: "端到端拓扑保持的气道解剖分析：叶/段/亚段层级标注 + 紧凑“解剖签名”（狭窄、扩张、扭曲度等）刻画疾病特异模式。ATM26 官方参考。", en: "End-to-end topology-preserving airway analysis: lobar/segmental/subsegmental labeling plus a compact 'anatomical signature' (stenosis, ectasia, tortuosity...) capturing disease-specific patterns. An ATM26 official reference." },
      arxiv: "2412.11039", doi: null,
      code: "https://github.com/EndoluminalSurgicalVision-IMR/AirMorph",
      tags: ["atlas", "topology"],
    },
  ],

  // ------------------------------------------------------------------- PAPERS
  PAPERS: [
    // ===== Foundational / classic segmentation =====
    {
      title: "AirwayNet: A Voxel-Connectivity Aware Approach for Accurate Airway Segmentation",
      authors: "Qin Y., Chen M., Zheng H., Gu Y., et al.",
      year: 2019, venue: "MICCAI 2019",
      category: "topology",
      idea: { zh: "将气道分割重构为“预测体素与26邻域的连通性”任务，缓解细支气管断裂，是连通性建模的奠基工作之一。", en: "Reframes airway segmentation as predicting each voxel's connectivity to its 26 neighbours, reducing bronchiole breakage — a foundational connectivity-modeling work." },
      arxiv: "1907.06852", doi: "10.1007/978-3-030-32226-7_24", code: null,
      tags: ["connectivity", "26-neighbour"],
    },
    {
      title: "Automatic Airway Segmentation from Computed Tomography using Robust and Efficient 3-D CNNs (bronchinet)",
      authors: "Garcia-Uceda A., Selvan R., Saghir Z., de Bruijne M., et al.",
      year: 2021, venue: "Scientific Reports 11:16001 (前身 MICCAI 2019)",
      category: "segmentation",
      idea: { zh: "轻量高效的 3D U-Net 变体，滑窗全气道分割，开源实现 bronchinet 被广泛用作基线。", en: "A lightweight, efficient 3D U-Net variant for sliding-window full-airway segmentation; the open-source bronchinet is a widely used baseline." },
      arxiv: "2103.16328", doi: "10.1038/s41598-021-95364-1",
      code: "https://github.com/antonioguj/bronchinet",
      tags: ["3D-UNet", "baseline"],
    },
    {
      title: "Alveolar-aware / Graph Refinement for Airway Segmentation (Juarez et al. GNN)",
      authors: "Garcia-Uceda Juarez A., Selvan R., et al.",
      year: 2019, venue: "MICCAI Workshop (GLMI)",
      category: "topology",
      idea: { zh: "在 CNN 分割后接图神经网络细化，沿气道图结构传播上下文以补全断裂分支。", en: "Refines CNN segmentation with a graph neural network that propagates context along the airway graph to reconnect broken branches." },
      arxiv: "1908.08588", doi: "10.1007/978-3-030-33327-0_70", code: null,
      tags: ["GNN", "refinement"],
    },
    {
      title: "Alleviating Class-imbalance for Airway Segmentation (WingsNet + General Union Loss)",
      authors: "Zheng H., Qin Y., Gu Y., Xie X., et al.",
      year: 2021, venue: "IEEE TMI 40(9)",
      category: "topology", star: true,
      idea: { zh: "提出 General Union Loss 缓解“大气道主导、小支气管被忽视”的梯度不平衡，配合 WingsNet 深监督显著提升远端分支检出。", en: "Introduces the General Union Loss to counter the gradient imbalance where large airways dominate and small bronchi are ignored; with WingsNet deep supervision it markedly improves distal-branch detection." },
      arxiv: "2011.14002", doi: "10.1109/TMI.2021.3078828",
      code: "https://github.com/haozheng-sjtu/3d-airway-segmentation",
      tags: ["class-imbalance", "union-loss"],
    },
    {
      title: "Learning Tubule-Sensitive CNNs for Pulmonary Airway and Artery-Vein Segmentation",
      authors: "Qin Y., Gu Y., Zheng H., et al.",
      year: 2021, venue: "IEEE TMI 40(6)",
      category: "topology",
      idea: { zh: "引入管状结构敏感（radial distance/tubular）监督，强化细长气道的连续性与分支保留。", en: "Adds tubular-structure-sensitive (radial-distance) supervision to strengthen the continuity and branch preservation of thin elongated airways." },
      arxiv: "2012.05767", doi: "10.1109/TMI.2021.3062280", code: null,
      tags: ["tubular", "radial-distance"],
    },
    {
      title: "clDice — A Novel Topology-Preserving Loss Function for Tubular Structure Segmentation",
      authors: "Shit S., Paetzold J.C., Menze B., et al.",
      year: 2021, venue: "CVPR 2021",
      category: "topology", star: true,
      idea: { zh: "基于软骨架的中心线 Dice 损失，可微分地保证管状/树状结构的连通性，成为血管与气道分割的通用拓扑损失。", en: "A soft-skeleton-based centerline Dice loss that differentiably preserves the connectivity of tubular/tree structures; a general topology loss for vessels and airways." },
      arxiv: "2003.07311", doi: "10.1109/CVPR46437.2021.01629",
      code: "https://github.com/jocpae/clDice",
      tags: ["clDice", "centerline-loss"],
    },
    {
      title: "CT Airway Segmentation via 2.5D Freeze-and-Grow Propagation",
      authors: "Nadeem S.A., Hoffman E.A., Comellas A.P., Saha P.K., et al.",
      year: 2021, venue: "IEEE TMI / MICCAI 系列",
      category: "topology",
      idea: { zh: "冻结已确信气道、逐步“生长”不确定区域的传播式分割，抑制泄漏同时延伸远端分支。", en: "Propagation-based segmentation that freezes confident airway and iteratively grows uncertain regions, suppressing leakage while extending distal branches." },
      arxiv: null, doi: "10.1109/TMI.2020.3025091", code: null,
      tags: ["freeze-and-grow", "leakage"],
    },
    {
      title: "Connectivity-Aware Airway Segmentation (break-fixing / connectivity-aware surrogate)",
      authors: "Zhang M., Gu Y., et al.",
      year: 2023, venue: "IEEE JBHI",
      category: "topology",
      idea: { zh: "以连通性为核心的代理任务修复分割断裂，提升气道树整体连通度。", en: "Repairs segmentation breaks with a connectivity-centric surrogate task, improving the overall connectivity of the airway tree." },
      arxiv: null, doi: null,
      code: "https://github.com/EndoluminalSurgicalVision-IMR/Connectivity-Aware-Airway-Segmentaion",
      tags: ["connectivity", "break-fixing"],
    },
    {
      title: "Fuzzy Attention Neural Network for Airway Segmentation (FANN)",
      authors: "Nan Y., Ser J.D., Walsh S., Yang G., et al.",
      year: 2023, venue: "IEEE TNNLS",
      category: "segmentation",
      idea: { zh: "模糊注意力 + 边界损失强化气道边界与细支气管，提升鲁棒性。", en: "Fuzzy attention plus a boundary loss strengthen airway boundaries and bronchioles, improving robustness against discontinuity." },
      arxiv: "2209.02048", doi: "10.1109/TNNLS.2023.3269523",
      code: "https://github.com/Nandayang/FANN-for-airway-segmentation",
      tags: ["attention", "boundary"],
    },
    {
      title: "Accurate Airway Tree Segmentation via Anatomy-Aware Multi-Class Segmentation and Topology-Guided Iterative Learning",
      authors: "Wang P., et al.",
      year: 2024, venue: "IEEE TMI",
      category: "topology",
      idea: { zh: "把二值分割改为解剖感知的多类分割，并用拓扑引导的迭代学习逐步修正，兼顾重叠与连通性。", en: "Recasts binary segmentation as anatomy-aware multi-class segmentation and refines it with topology-guided iterative learning, balancing overlap and connectivity." },
      arxiv: null, doi: "10.1109/TMI.2024.3419707", code: null,
      tags: ["multi-class", "iterative"],
    },

    // ===== 2024–2026 segmentation =====
    {
      title: "Implicit Representation Embraces Challenging Attributes of Pulmonary Airway Tree Structures (DGCI)",
      authors: "Zhang M., et al.",
      year: 2024, venue: "MICCAI 2024",
      category: "transformer",
      idea: { zh: "用隐式神经表示刻画气道树的高分辨率细支气管与复杂拓扑，突破体素网格分辨率限制。", en: "Uses an implicit neural representation to capture high-resolution bronchioles and complex topology beyond voxel-grid resolution limits." },
      arxiv: null, doi: null,
      code: "https://github.com/EndoluminalSurgicalVision-IMR/DGCI",
      tags: ["implicit", "INR"],
    },
    {
      title: "Airway Segmentation Based on Topological Structure Enhancement Using Multi-task Learning",
      authors: "Yang X., et al.",
      year: 2024, venue: "MICCAI 2024",
      category: "topology",
      idea: { zh: "多任务学习联合分割与拓扑结构增强分支，强化气道树骨架的结构一致性。", en: "Multi-task learning jointly does segmentation and topology-enhancement branches, reinforcing the structural consistency of the airway-tree skeleton." },
      arxiv: null, doi: null,
      code: "https://github.com/xyang-11/airway_seg",
      tags: ["multi-task", "topology-enhance"],
    },
    {
      title: "Multi-Stage Airway Segmentation in Lung CT Based on Multi-scale Nested Residual UNet",
      authors: "Yang B., et al.",
      year: 2024, venue: "arXiv preprint",
      category: "segmentation",
      idea: { zh: "多阶段、多尺度嵌套残差 U-Net，逐级捕获从主气道到细支气管的多尺度结构。", en: "A multi-stage, multi-scale nested residual U-Net that progressively captures structures from main airways to bronchioles." },
      arxiv: "2410.18456", doi: null, code: null,
      tags: ["multi-scale", "nested-UNet"],
    },
    {
      title: "DMRN: A Dynamical Multi-Order Response Network for Robust Lung Airway Segmentation",
      authors: "Zhang et al.",
      year: 2025, venue: "WACV 2025",
      category: "segmentation",
      idea: { zh: "动态多阶响应网络，面向不同气道形态提升分割鲁棒性。", en: "A dynamical multi-order response network that improves segmentation robustness across airway morphologies." },
      arxiv: null, doi: null,
      url: "https://openaccess.thecvf.com/content/WACV2025/papers/Zhang_DMRN_A_Dynamical_Multi-Order_Response_Network_for_the_Robust_Lung_WACV_2025_paper.pdf",
      code: null, tags: ["robustness"],
    },
    {
      title: "MGASM-Net: Morphology-Guided Multi-task Network with Anatomic Spatial Mamba for 3D Airway Segmentation",
      authors: "(Springer) — 见原文", // [unverified] first author
      year: 2025, venue: "Complex & Intelligent Systems",
      category: "transformer",
      idea: { zh: "以 Mamba 状态空间为骨干、形态学引导的多任务网络进行 3D 气道分割。", en: "A morphology-guided multi-task network with a Mamba state-space backbone for 3D airway segmentation." },
      arxiv: null, doi: "10.1007/s40747-025-01995-6", code: null,
      tags: ["Mamba", "SSM"],
    },
    {
      title: "RepAir: A Framework for Airway Segmentation and Discontinuity Correction in CT",
      authors: "Oyer J.M., et al. (Galbán/Ram group)",
      year: 2026, venue: "arXiv preprint (2025-11, rev. 2026-02)",
      category: "topology",
      idea: { zh: "三阶段流水线：nnU-Net 分割 + 拓扑校正重连断裂分支，在 ATM'22 与 AeroPath 上评估。", en: "A three-stage pipeline pairing nnU-Net segmentation with topology correction to reconnect broken branches, evaluated on ATM'22 and AeroPath." },
      arxiv: "2511.14649", doi: null, code: null,
      tags: ["nnU-Net", "discontinuity"],
    },
    {
      title: "Progressive Curriculum Learning with Scale-Enhanced U-Net for Continuous Airway Segmentation",
      authors: "见原文",
      year: 2025, venue: "2025 (PMC12821885)",
      category: "segmentation",
      idea: { zh: "渐进式课程学习 + 尺度增强 U-Net，改善细支气管连续性。", en: "Progressive curriculum learning with a scale-enhanced U-Net to improve bronchiole continuity." },
      arxiv: null, doi: null,
      code: "https://github.com/Beryl2000/SE-UNet-AirSeg", // [repo–paper link unverified]
      tags: ["curriculum", "continuity"],
    },
    {
      title: "ExpTopo: Explicit Topological Modeling for Bronchus Segmentation",
      authors: "见原文",
      year: 2025, venue: "IEEE ISBI 2025",
      category: "topology",
      idea: { zh: "显式拓扑建模用于支气管分割。", en: "Explicit topological modeling for bronchus segmentation." },
      arxiv: null, doi: "10.1109/ISBI60581.2025.10980891", code: null,
      tags: ["explicit-topology"],
    },

    // ===== Anatomical labeling (Track 2) =====
    {
      title: "AirwayFormer: Structure-Aware Boundary-Adaptive Transformers for Airway Anatomical Labeling",
      authors: "Yu W., Zheng H., Gu Y., et al.",
      year: 2023, venue: "MICCAI 2023",
      category: "labeling", star: true,
      idea: { zh: "结构感知、边界自适应的 Transformer 为气道分支做解剖命名，建模气道树全局拓扑关系。", en: "A structure-aware, boundary-adaptive Transformer that names airway branches while modeling the global topology of the airway tree." },
      arxiv: null, doi: null,
      code: "https://github.com/EndoluminalSurgicalVision-IMR/AirwayFormer",
      tags: ["transformer", "branch-naming"],
    },
    {
      title: "TNN: Tree Neural Network for Airway Anatomical Labeling",
      authors: "Yu W., Zheng H., Zhang M., Gu Y., et al.",
      year: 2022, venue: "IEEE TMI 42(1)",
      category: "labeling",
      idea: { zh: "树神经网络沿气道树层级传播特征，为段/亚段支气管分配标准名称，是气道命名的奠基工作。", en: "A tree neural network that propagates features along the airway-tree hierarchy to assign standard names to segmental/subsegmental bronchi — a foundational labeling work." },
      arxiv: null, doi: "10.1109/TMI.2022.3204538",
      code: "https://github.com/haozheng-sjtu/airway-labeling",
      tags: ["tree-NN", "foundational"],
    },
    {
      title: "Efficient Anatomical Labeling of Pulmonary Tree Structures via Deep Point-Graph Representation-based Implicit Fields",
      authors: "Xie K., et al.",
      year: 2024, venue: "Medical Image Analysis",
      category: "labeling",
      idea: { zh: "点-图表示 + 隐式场高效标注气道/血管等肺部树状结构的解剖名称。", en: "A point-graph representation with implicit fields for efficient anatomical labeling of pulmonary tree structures (airways/vessels)." },
      arxiv: null, doi: "10.1016/j.media.2024.103367",
      code: "https://github.com/M3DV/pulmonary-tree-labeling",
      tags: ["point-graph", "implicit"],
    },
    {
      title: "Structure and Position-Aware Graph Neural Network for Airway Labeling",
      authors: "见原文",
      year: 2024, venue: "Medical Image Analysis",
      category: "labeling",
      idea: { zh: "结构与位置感知的图神经网络进行气道分支标注。", en: "A structure- and position-aware graph neural network for airway branch labeling." },
      arxiv: null, doi: "10.1016/j.media.2024.103286", code: null,
      tags: ["GNN", "position-aware"],
    },

    // ===== Navigation / centerline =====
    {
      title: "Harnessing Foundation Models for Robust and Generalizable 6-DOF Bronchoscopy Localization",
      authors: "见原文",
      year: 2025, venue: "arXiv preprint",
      category: "navigation",
      idea: { zh: "利用基础模型做支气管镜 6 自由度位姿估计，提升定位的鲁棒性与泛化。", en: "Uses foundation models for 6-DOF bronchoscope pose estimation, improving localization robustness and generalization." },
      arxiv: "2505.24249", doi: null, code: null,
      tags: ["foundation-model", "6-DOF"],
    },
    {
      title: "PANS: Probabilistic Airway Navigation System for Real-time Robust Bronchoscope Localization",
      authors: "见原文",
      year: 2024, venue: "arXiv preprint",
      category: "navigation",
      idea: { zh: "概率式气道导航系统，实时鲁棒地定位支气管镜。", en: "A probabilistic airway navigation system for real-time, robust bronchoscope localization." },
      arxiv: "2407.05554", doi: null, code: null,
      tags: ["localization", "probabilistic"],
    },
    {
      title: "BronchoTrack: Airway Lumen Tracking for Branch-Level Bronchoscopic Localization",
      authors: "见原文",
      year: 2024, venue: "arXiv preprint",
      category: "navigation",
      idea: { zh: "气道管腔跟踪实现分支级支气管镜定位。", en: "Airway lumen tracking that achieves branch-level bronchoscopic localization." },
      arxiv: "2402.12763", doi: null, code: null,
      tags: ["tracking", "lumen"],
    },
    {
      title: "Discovery of Peripheral Airway Beyond Incomplete CT Annotations for Navigational Bronchoscopy",
      authors: "见原文",
      year: 2026, venue: "IEEE TMI",
      category: "navigation",
      idea: { zh: "从不完整 CT 标注中恢复外周细支气管，服务导航支气管镜。", en: "Recovers peripheral bronchioles missed by incomplete CT annotations, serving navigational bronchoscopy." },
      arxiv: null, doi: null, code: null, // DOI [unverified]
      tags: ["peripheral-airway"],
    },

    // ===== Datasets / challenges =====
    {
      title: "AeroPath: An Airway Segmentation Benchmark Dataset with Challenging Pathology",
      authors: "Støverud K.-H., et al.",
      year: 2023, venue: "arXiv (dataset)",
      category: "dataset",
      idea: { zh: "含挑战性病理的气道分割公开基准数据集，2024–25 多项工作使用。", en: "A public airway-segmentation benchmark with challenging pathology, used by many 2024–25 works." },
      arxiv: null, doi: null,
      code: "https://github.com/raidionics/AeroPath",
      tags: ["dataset", "pathology"],
    },
    {
      title: "AIIB23: Airway-Informed Quantitative CT Imaging Biomarkers in Pulmonary Fibrosis",
      authors: "Nan Y., et al.",
      year: 2024, venue: "Medical Image Analysis",
      category: "dataset",
      idea: { zh: "肺纤维化气道影像生物标志物挑战赛，与 ATM 系列互补的气道基准。", en: "An airway imaging-biomarker challenge for pulmonary fibrosis, complementary to the ATM series." },
      arxiv: null, doi: null, code: null,
      tags: ["challenge", "fibrosis"],
    },
    {
      title: "Topology Repairing of Disconnected Pulmonary Airways and Vessels: Baselines and a Dataset",
      authors: "Weng Z., et al.",
      year: 2023, venue: "MICCAI 2023",
      category: "dataset",
      idea: { zh: "断裂气道/血管拓扑修复的数据集与基线，与 ATM26 的拓扑评价直接相关。", en: "A dataset and baselines for repairing disconnected airways/vessels, directly relevant to ATM26's topology metrics." },
      arxiv: null, doi: null, code: null,
      tags: ["topology-repair", "dataset"],
    },
  ],

  // ------------------------------------------------------------------ DATASETS
  DATASETS: [
    { name: { zh: "ATM26 官方数据集 (Zenodo)", en: "ATM26 official dataset (Zenodo)" }, year: 2026,
      desc: { zh: "ATM26 训练数据 Task1（二值分割 299 例）+ Task2（分支标注 118 例，Task2 ⊂ Task1）。胸部薄层 CT，.mha 格式。", en: "ATM26 training data: Task1 (binary segmentation, 299 cases) + Task2 (branch labeling, 118 cases, Task2 ⊂ Task1). Thin-slice chest CT, .mha format." },
      url: "https://zenodo.org/records/19731649", tags: ["Track1", "Track2", "MICCAI2026"] },
    { name: { zh: "ATM'22 训练数据 (Zenodo)", en: "ATM'22 training data (Zenodo)" }, year: 2022,
      desc: { zh: "ATM'22 多中心气道分割挑战赛训练集，ATM26 前身。", en: "Training set of the ATM'22 multi-site airway segmentation challenge, the predecessor of ATM26." },
      url: "https://zenodo.org/records/6590745", tags: ["ATM22", "binary-seg"] },
    { name: { zh: "AeroPath", en: "AeroPath" }, year: 2023,
      desc: { zh: "含挑战性病理的气道分割基准，附完整分割与工具。", en: "An airway segmentation benchmark with challenging pathology, shipped with full masks and tooling." },
      url: "https://github.com/raidionics/AeroPath", code: "https://github.com/raidionics/AeroPath", tags: ["pathology"] },
    { name: { zh: "EXACT'09", en: "EXACT'09" }, year: 2009,
      desc: { zh: "经典气道提取挑战赛（Extraction of Airways from CT），拓扑/泄漏评价方法学的源头之一。", en: "The classic Extraction of Airways from CT challenge; a source of topology/leakage evaluation methodology." },
      url: "http://image.diku.dk/exact/", tags: ["classic", "benchmark"] },
    { name: { zh: "LIDC-IDRI", en: "LIDC-IDRI" }, year: 2011,
      desc: { zh: "大规模胸部 CT 公开库，常用于气道/结节相关预训练与外部验证。", en: "A large public chest CT repository, commonly used for airway/nodule pretraining and external validation." },
      url: "https://www.cancerimagingarchive.net/collection/lidc-idri/", tags: ["chest-CT", "public"] },
  ],

  // -------------------------------------------------------------- CHALLENGES
  CHALLENGES: [
    { name: { zh: "ATM26 — Airway Tree Modeling 2026", en: "ATM26 — Airway Tree Modeling 2026" }, year: 2026,
      desc: { zh: "MICCAI 2026 挑战赛。Track 1 二值气道分割 + Track 2 分支级解剖标注，真实采集条件下评估拓扑正确性与连通性。当前气道树建模主基准。", en: "MICCAI 2026 challenge. Track 1 binary airway segmentation + Track 2 branch-wise anatomical labeling, evaluating topology and connectivity under realistic acquisition. The current mainline airway-tree-modeling benchmark." },
      url: "https://atm26.grand-challenge.org/homepage/", tags: ["MICCAI2026", "seg", "labeling"] },
    { name: { zh: "ATM'22 — Multi-site Airway Tree Modeling", en: "ATM'22 — Multi-site Airway Tree Modeling" }, year: 2022,
      desc: { zh: "MICCAI 2022 多中心/多域气道分割挑战赛（500 例 CT），首个大规模公开气道分割基准，引入树长/分支检出等拓扑指标。ATM26 前身。", en: "MICCAI 2022 multi-site/multi-domain airway segmentation challenge (500 CT scans); the first large public airway segmentation benchmark, introducing tree-length/branch-detected topology metrics. Predecessor of ATM26." },
      url: "https://atm22.grand-challenge.org/", paper: "https://doi.org/10.1016/j.media.2023.102957", tags: ["MICCAI2022", "binary-seg"] },
    { name: { zh: "AIIB23 — Airway-Informed Imaging Biomarkers", en: "AIIB23 — Airway-Informed Imaging Biomarkers" }, year: 2023,
      desc: { zh: "面向肺纤维化的气道影像定量生物标志物挑战赛，与 ATM 系列互补。", en: "A quantitative airway imaging-biomarker challenge for pulmonary fibrosis, complementary to the ATM series." },
      url: "https://codalab.lisn.upsaclay.fr/competitions/13238", tags: ["fibrosis", "biomarker"] },
    { name: { zh: "EXACT'09 — Extraction of Airways from CT", en: "EXACT'09 — Extraction of Airways from CT" }, year: 2009,
      desc: { zh: "经典气道提取挑战赛，泄漏/树长评价方法学的源头，奠定了气道分割评价范式。", en: "The classic airway extraction challenge; the origin of leakage/tree-length evaluation and the airway segmentation evaluation paradigm." },
      url: "http://image.diku.dk/exact/", tags: ["classic", "benchmark"] },
    { name: { zh: "AeroPath (benchmark)", en: "AeroPath (benchmark)" }, year: 2023,
      desc: { zh: "含挑战性病理的公开气道分割基准数据集，可作为跨域测试。", en: "A public airway segmentation benchmark dataset with challenging pathology, usable as a cross-domain test." },
      url: "https://github.com/raidionics/AeroPath", code: "https://github.com/raidionics/AeroPath", tags: ["pathology", "benchmark"] },
  ],

  // --------------------------------------------------------------------- TOOLS
  TOOLS: [
    { name: { zh: "ATM-22-Related-Work (主索引)", en: "ATM-22-Related-Work (master index)" },
      desc: { zh: "EndoluminalSurgicalVision-IMR 维护的气道建模文献/代码精选列表，覆盖 2012→2025 的分割、标注、拓扑修复、导航。本站的主要种子来源。", en: "A curated airway-modeling paper/code list maintained by EndoluminalSurgicalVision-IMR, covering 2012→2025 segmentation, labeling, topology repair and navigation. The main seed of this site." },
      url: "https://github.com/EndoluminalSurgicalVision-IMR/ATM-22-Related-Work",
      code: "https://github.com/EndoluminalSurgicalVision-IMR/ATM-22-Related-Work", tags: ["awesome-list", "seed"] },
    { name: { zh: "nnU-Net", en: "nnU-Net" }, desc: { zh: "自配置医学图像分割框架，气道分割最常用的强基线与流水线。", en: "A self-configuring medical image segmentation framework; the most common strong baseline and pipeline for airway segmentation." },
      url: "https://github.com/MIC-DKFZ/nnUNet", code: "https://github.com/MIC-DKFZ/nnUNet", tags: ["framework", "baseline"] },
    { name: { zh: "clDice loss", en: "clDice loss" }, desc: { zh: "拓扑保持的中心线 Dice 损失官方实现，可直接用于气道训练。", en: "The official topology-preserving centerline Dice loss, usable directly for airway training." },
      url: "https://github.com/jocpae/clDice", code: "https://github.com/jocpae/clDice", tags: ["loss", "topology"] },
    { name: { zh: "bronchinet", en: "bronchinet" }, desc: { zh: "Garcia-Uceda 等的 3D CNN 气道分割开源实现，经典基线。", en: "Garcia-Uceda et al.'s open-source 3D CNN airway segmentation implementation; a classic baseline." },
      url: "https://github.com/antonioguj/bronchinet", code: "https://github.com/antonioguj/bronchinet", tags: ["baseline", "3D-CNN"] },
    { name: { zh: "pulmonary-tree-labeling", en: "pulmonary-tree-labeling" }, desc: { zh: "肺部树状结构（气道/血管）解剖标注的点-图/隐式场实现。", en: "Point-graph / implicit-field implementation for anatomical labeling of pulmonary tree structures (airways/vessels)." },
      url: "https://github.com/M3DV/pulmonary-tree-labeling", code: "https://github.com/M3DV/pulmonary-tree-labeling", tags: ["labeling"] },
    { name: { zh: "MEDPSeg", en: "MEDPSeg" }, desc: { zh: "肺/气道/病变多任务分割工具。", en: "A multi-task lung/airway/lesion segmentation tool." },
      url: "https://github.com/miclab-unicamp/medpseg", code: "https://github.com/miclab-unicamp/medpseg", tags: ["multi-task"] },
  ],

  // -------------------------------------------------- GITHUB LIVE SEARCH QUERIES
  // 供“实时检索”下拉；q 为 GitHub search API 的 q 参数（+ 会被自动 URL 编码）。
  GH_QUERIES: [
    { label: { zh: "airway segmentation（近两年，按更新）", en: "airway segmentation (last 2y, by update)" }, q: "airway segmentation in:name,description,readme pushed:>2024-01-01" },
    { label: { zh: "airway tree modeling", en: "airway tree modeling" }, q: "airway tree modeling in:name,description,readme" },
    { label: { zh: "airway segmentation CT deep learning", en: "airway segmentation CT deep learning" }, q: "airway segmentation CT deep learning in:name,description,readme" },
    { label: { zh: "bronchus segmentation", en: "bronchus segmentation" }, q: "bronchus segmentation in:name,description,readme" },
    { label: { zh: "airway labeling（解剖命名）", en: "airway labeling (anatomical naming)" }, q: "airway labeling in:name,description,readme" },
    { label: { zh: "bronchoscopy navigation", en: "bronchoscopy navigation" }, q: "bronchoscopy navigation in:name,description,readme" },
    { label: { zh: "airway centerline", en: "airway centerline" }, q: "airway centerline in:name,description,readme" },
    { label: { zh: "pulmonary airway (Python, star>2)", en: "pulmonary airway (Python, star>2)" }, q: "pulmonary airway in:name,description,readme language:Python stars:>2" },
    { label: { zh: "airway tree challenge (ATM/EXACT)", en: "airway tree challenge (ATM/EXACT)" }, q: "airway tree challenge in:name,description,readme" },
    { label: { zh: "topic: medical-image-segmentation + airway", en: "topic: medical-image-segmentation + airway" }, q: "airway topic:medical-image-segmentation" },
    { label: { zh: "topic: airway-segmentation", en: "topic: airway-segmentation" }, q: "topic:airway-segmentation" },
    { label: { zh: "topic: chest-ct", en: "topic: chest-ct" }, q: "topic:chest-ct" },
    { label: { zh: "clDice / topology tubular loss", en: "clDice / topology tubular loss" }, q: "clDice OR centerline dice tubular in:name,description,readme" },
  ],
};
